### ISSUE TITLE
Iron gear recipe is not showing 

### ISSUE THREAD

**Issue by crimso** [WanionCane/UniDict#51]
Hello 

I am playing with Direwolf 20s FTB 1.12 MOD pack and plus some extra mods for example Hammer Core, Hammer Metals and I have a problem with some items, for example Iron Gear recipe I can not craft If I have GEAR written/enables in your config file (print screens below). Deleting the GEAR I can craft Thermal Foundation and Hammer Core/Metal gears separately. I dont know if its a bug or something I just informing you :) 

[https://imgur.com/WhUXnwO](url)
[https://imgur.com/LHrxqk3](url)

Please keep up the good work I really like your MOD :)

**Comment by WanionCane** [comment]
seems to have something weird, I will take a look =P

**Comment by WanionCane** [comment]
I tried here and it is working fine.
UniDict version: 1.12.2-1.4 (which I just released).
![2017-11-28_11 44 50](https://user-images.githubusercontent.com/10801965/33322804-9e06e4be-d431-11e7-95e1-86b974bbac5c.png)

**Comment by crimso** [comment]
Hello,

OK OK super I will try it after work If it will be on curseforge.

Thank you

**Comment by crimso** [comment]
Hello,

so I updated your mod but somehow is still not working for me :/ check pictures below:

[https://imgur.com/COI5JRh](url)
[https://imgur.com/VfYQg6r](url)
[https://imgur.com/driQCT2](url)
[https://imgur.com/hQgY5Nl](url)

thermal expansion and hammer core/ hammer metals maybe they can not work together :/

I am using the Direwolf 20s 1.12 pack

but doesnt matter I will just delete GEAR in config file :)

Thank you for your support :)

**Comment by WanionCane** [comment]
I don't know why it is not working =/

**Comment by WanionCane** [comment]
still nothing? :(

**Comment by crimso** [comment]
Hello,

I will test it and let you know :)

**Comment by WanionCane** [comment]
thanks :D

**Comment by crimso** [comment]
[https://imgur.com/a/e7Xx5](url)

Hello, please check the print screens, now I can not see hammer metals/core gears, only thermal foundation gears, but the iron gear is still not working :/ Also you can check the unidict config.

**Comment by WanionCane** [comment]
oh hey, question, is your forge updated? I had saw a few recipe issues with an outdated forge.

**Comment by WanionCane** [comment]
about you only being able to see thermal foundation gear, I fixed in the last release the "autoHideInJEI" feature, it was for a long time broken lol.

**Comment by crimso** [comment]
yest I have the lates forge 2559

**Comment by WanionCane** [comment]
this is super weird, is this happening just in DireWolf20 modpack?

**Comment by crimso** [comment]
honestly I didnt try other packs yet, but I will try with others and I let you know today or tomorrow :)

**Comment by WanionCane** [comment]
hello again, I forgot to ask are you playing in a server?

**Comment by crimso** [comment]
Hello,

No, normal single player world.

**Comment by WanionCane** [comment]
really werid, I downloaded the pack and here is the result:
![2017-12-05_10 29 59](https://user-images.githubusercontent.com/10801965/33607196-688e6bec-d9a7-11e7-94cb-f3223dc7c01c.png)

so... I really don't know what is causing this issue =/

**Comment by crimso** [comment]
could you try it out with Hammer metals MOD and Hammer Core MOD? Also If you want I can upload my instance with all the mods and with my world and you can test it if you want. Maybe it will help to you :)

**Comment by WanionCane** [comment]
tried here with Hammer Metals & Hammer Core, and indeed it isn't working
![2017-12-05_11 05 49](https://user-images.githubusercontent.com/10801965/33608674-601b7a54-d9ac-11e7-8b9c-e877be1e93f0.png)
I will try somethings to see if I can fix this. =P

**Comment by crimso** [comment]
hahaaa :D super noh :)

**Comment by WanionCane** [comment]
I tried a lot, and I couldn't make it to work =/
hey @APengu, sorry to bother you with this, but you have any clue about what is causing this issue?

**Comment by TehenoPengin** [comment]
So weird.... No ideas, really sorry :/
